### ISSUE TITLE
NetClient can override HandleMessage?

### ISSUE THREAD

**Issue by seanmars** [Eastrall/Ether.Network#107]
Really don't know how to use.
The `NetClient` just can override `OnConnected`, `OnDisconnected`, `OnSocketError`.
The `HandleMessage` has nothing in source code, and it is already overrided, how to use it?

**Comment by Eastrall** [comment]
Hello,

`NetClient` can override `HandleMessage`. The difference between `HandleMessage` and the other methods (`OnConencted`, `OnDisconnected` and `OnSocketError`) is that `HandleMessage` is `public` and the others are `protected`.

To override `HandleMessage` just do:

```cs
public class MyClient : NetClient
{
    ...

    public override void HandleMessage(INetPacketStream packet)
    {
        // Insert code here
    }
}
```

**Comment by seanmars** [comment]
Hi,

So sorry, that's my bad. My vs code complier error. Thanks you a lot.

**Comment by Eastrall** [comment]
You're welcome. Closing issue.
