### ISSUE TITLE
NetPacket abstraction

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Ether.Network#15]
In some cases, people want to format their packets differently than our current structure:

- Packet Size
- Packet Data

We can allow people to do their own packet implementation like : 

- Packet header
- Packet Size
- Packet Data

For this, we must be able to do code like this:

```c#
public MyPacket : NetPacket
{
    // ...
}
```

We also need to find a way for the user to do a custom `NetPacket.Split`. If the structure changes and if we recieve multiple packets at once (merged packets), we'll need a custom treatment of the incoming packets.

**Comment by Eastrall** [comment]
For the custom `NetPacket.Split` I thought about creating an `Action<byte[]>` property inside `NetServer` class set by default to `NetPacket.Split` method.

So the developer can easily override the `Split` method.

Second idea is to create a virtual method in `NetServer` class that returns a `NetPacket[]`, so this method can be override in the `NetServer<...>` implementations like:

```c#
// Ether.Network class
class NetServer<T>
{
    protected virtual NetPacket[] SplitPackets(byte[] buffer)
    {
        return NetPacket.Split(buffer);
    }
}

// Developer class
public class Server : NetServer<...>
{
    protected override NetPacket[] SplitPackets(byte[] buffer)
    {
        return CustomSplitPacket(buffer);
        // we don't use base.SplitPackets because we want a custom process.
    }
    
    private NetPacket[] CustimSplitPacket(byte[] buffer)
    {
        var packets = new List<NetPacket>();
       
        // TODO

       return packets.ToArray();
    }
}
```

**Comment by aloisdg** [comment]
private NetPacket[] CustimSplitPacket(byte[] buffer)
    {
        var packets = new List<NetPacket>();

        // TODO

       return packets.ToArray();
    }

You could use interface

    // or IEnumerable<NetPacket>
    private IReadOnlyCollection<NetPacket> CustimSplitPacket(IReadOnlyCollection<byte> buffer)
    {
        var packets = new List<NetPacket>();

        // TODO

       return packets;
    }

**Comment by Eastrall** [comment]
Using a `IEnumerable<T>` removes the cast in the `CustomSplitPackets` methods. `IReadOnlyCollection<byte>` should also be ok since we don't need to change the data in it.

I've changed the `NetPacket` class name into `NetPacketBase` which is an `abstract class`.
We still have the `NetPacket` class but now it inherits from the `NetPacketBase` where all the packet memory management is done.

So the NetPacket is our own implementation and vision of packets. 

```c#
public class NetPacket : NetPacketBase
    {
        public override Byte[] Buffer
        {
            get
            {
                this.memoryWriter.Seek(0, SeekOrigin.Begin);
                this.Write(this.Size);
                this.memoryWriter.Seek(this.Size, SeekOrigin.Begin);

                return this.GetBuffer();
            }
        }

        public NetPacket()
            : base()
        {
            this.Write(0); // Packet size
        }

        public NetPacket(byte[] buffer)
            : base(buffer)
        {
        }
}
```

If tommorow the developper wants to create his own packet, he just have to create his own class and inherit from `NetPacketBase` 😄 
Much easier this way I think.

**Comment by Eastrall** [comment]
Released in version 1.1.0

**Comment by aloisdg** [comment]
[semvered](http://semver.org/)?

**Comment by Eastrall** [comment]
Thanks for the link! Do you think the version release should be 2.**.** ? Since there is some changes to the `NetServer` (Events to abstract methods)

**Comment by aloisdg** [comment]
@Eastrall Yes I think. But you can wait for your v2 before moving to semver. [GitVersion](https://github.com/GitTools/GitVersion) may help you.

**Comment by Eastrall** [comment]
Didin't knew about GitVersion, looks very interesting! Thanks

**Comment by aloisdg** [comment]
You are welcome :)
