### ISSUE TITLE
Git commit message shouldn't be longer than 50 chars.

### ISSUE THREAD

**Issue by aloisdg** [Eastrall/Ether.Network#18]
It is far easier to read afterwards 😊

**Comment by Eastrall** [comment]
Yes you're right 😉 
I'll write short commit names from now

**Comment by aloisdg** [comment]
Tips:

- http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
- http://chris.beams.io/posts/git-commit/
- https://github.com/commitizen/cz-cli
