### ISSUE TITLE
client.Send() not working if too frequently used

### ISSUE THREAD

**Issue by regaaa** [Eastrall/Ether.Network#35]
Hi,

thx for this small but great lib. Considering the following code:

```c#
var client = new MyClient("127.0.0.1", 8888, 4096);
client.Connect();
Console.WriteLine("Enter a message and press enter...");
int i = 0;

while (i < 2)
{
    string input = "That is a test "+i;	

    if (input == "quit") 
    {
        break;   
    }

    if (input!=null)
    {
                using (var packet = new NetPacket())
		{
			packet.Write(input);

			client.Send(packet);
		}
    }

    i++;
}

client.Disconnect();
```

That will throw an error message that the Options is already in process on the client.Send(paket) line. How can I handle that right? For while i < 1 there is no error at all.

Thx in advance.

**Comment by Eastrall** [comment]
Hello, thank you for you feedback. It seems that is a bug inside the `NetClient` socket async management.
I will look into it and apply a patch shortly.

**Comment by Eastrall** [comment]
After some researches, I noticed that the `NetPacket` buffer size was wrong. I fixed it in commit : https://github.com/Eastrall/Ether.Network/commit/5aadc4a3e58eeb44999f29977c3bfd0e32dfa358 
But I will need to do more tests.
With the `develop` branch you can now send ~200 packets in `while(true)` loop. Another problem has been detected on the server side now when the recieved buffer is grather than the buffer size defined in the `NetServer` configuration. I will look into the `BufferManager` class to re-alocate memory in that case.

**Comment by regaaa** [comment]
Hey, thank you so much. I will give it a try and then report.

**Comment by Eastrall** [comment]
Solved with commit: 8414b6d980174dd16ea5d75b24432fad4c7aec6d

**Comment by Altiano** [comment]
Is the buffer in `byte` or `KiloByte` ?
Can I use `32 * 1024` as buffer for file transfer ?

**Comment by Eastrall** [comment]
The buffer is always in `byte`
