### ISSUE TITLE
NetPacketMethods Byte Array

### ISSUE THREAD

**Issue by RajanGrewal** [Eastrall/Ether.Network#37]
Writing a byte array just writes the bytes but reading them reads an int as size first

**Comment by Eastrall** [comment]
Hello, yes you are right. This is a bug, it shouldn't read the size first. The correct behavior would be to specify the amount of bytes you want to read like: 
```c#
packet.Read<byte[]>(10);
```

Thanks for the feedback. I will look into this soon enough.

**Comment by Eastrall** [comment]
I maybe came up with a solution. The best thing I could come up with is to create another `Read` method but this one will take the amount you want to read and return you an array.

```c#
public virtual T[] Read<T>(int amount)
{
    if (this._state != PacketStateType.Read)
        throw new InvalidOperationException("Packet is in write-only mode.");

    var type = typeof(T);

    if (type == typeof(byte))
        return this.MemoryReader.ReadBytes(amount) as T[];

    return default(T[]);
}
```

So you can use it like this:
```c#
byte[] byteArray = packet.Read<byte>(10);
```

**Comment by RajanGrewal** [comment]
Cool. Also maybe in future look into using https://github.com/DotNetCross/Memory.Unsafe for read and writing instead of a manual case for every type

**Comment by Eastrall** [comment]
Thanks for the link. I reopen the issue since it's not solved yet.

**Comment by Eastrall** [comment]
Done in : https://github.com/Eastrall/Ether.Network/pull/39
