### ISSUE TITLE
messageData.User.Socket.SendAsync(writeEventArgs)

### ISSUE THREAD

**Issue by wudiliujie** [Eastrall/Ether.Network#46]
messageData.User.Socket.SendAsync(writeEventArgs)  返回false的时候，不会触发IO_Completed，需要手动触发一下 IO_Completed

**Comment by Eastrall** [comment]
Hi, thank you for testing Ether.Network and opening an issue on our GitHub repository. In order to help you, can you describe your problem in english so everyone can understand your problem and bring solutions.

**Comment by Eastrall** [comment]
I used Google Translate to understand what was the problem you were talking about, and yes, when the `SendAsync()` methods returns `false` is that the action has been processed in a synchronous context, so the `IO_Completed` event is not fired.
So, in PR #49 I have fixed this issue by checking the return value of `SendAsync` on `NetServer` and `NetClient`.
