### ISSUE TITLE
Async Client Connect

### ISSUE THREAD

**Issue by ghost** [Eastrall/Ether.Network#57]
Yup, self explained... Why not implement that async also in the NetClient. :P

**Comment by Eastrall** [comment]
I think I am going to introduce a configuration class like the `NetServerConfiguration`.

But now, we will have two classes for the server part (`NetServer` and `NetServerConfiguration`) and for the client part (`NetClient` and `NetClientConfiguration`), so I was thinking about reorganizing the solution.

Maybe something like a `Ether.Network.Server` and `Ether.Network.Client` namespace that holds the everything related to the server and client.

**Comment by Eastrall** [comment]
The project structure has been done with PR: #67 

We can now introduce the `NetClientConfiguration` class.

**Comment by lRaikeNl** [comment]
Isn't this implemented already? I think this can be closed.

**Comment by Eastrall** [comment]
Yes indeed, this PR is solved, thank you for reporting.

Closing.
