### ISSUE TITLE
Add Packet Header to INetPacketStream

### ISSUE THREAD

**Issue by Yothri** [Eastrall/Ether.Network#64]
Hi,

Not sure if that's not already possible but I somehow need to get access to the packet header bytes in the `HandleMessage(INetPacketStream stream)` method. In my scenario, I not only need the header to read the actual payload length, no it also contains a byte telling whether it is a ping packet. And in Packet Processor I cant reply with a Ping Packet. So would it make sense to add a `byte[] Header;` field to the INetPacketStream to have access to the header bytes?

Thanks in advance.

**Comment by Eastrall** [comment]
Solved in PR #65
