### ISSUE TITLE
Can't figure out how to send a generic buffer

### ISSUE THREAD

**Issue by neosatus** [Eastrall/Ether.Network#74]
Hi, I was looking around for a Networking library to replace UNet in my Unity game server so I can run it as a standalone. I really liked the design of this one but I'm having trouble getting it to pass my already Serialized buffer from one side to the other. The buffer never actually sets and is throwing a NullReferenceException. Connecting works fine though. Here's my current code:

### Client Send
````
var packet = new Packet(PacketTypes.CommandPacket, new Dictionary<CommandTypes, object> {{ CommandTypes.DebugLogin, 1 }});  
var buffer = Serializer.Serialize(packet);  
var netPacket = new NetPacket();  
netPacket.Write(buffer);  
Send(netPacket);
````

### Server Receive
````
if (packet == null || packet.Buffer == null || packet.Buffer.Length == 0)
{
    Console.WriteLine("Packet was empty!");
    return;
}
            
var recv = (Packet)Serializer.Deserialize(packet.Buffer);
if (recv != null) Player.ProcessCommand(recv);
````

It's currently crashing on the `packet.Buffer == null` condition.

**Comment by Eastrall** [comment]
Hi, are you using the version on `develop` branch or the pre-release 2.1.0 ?

What I suggest to do is when you connect to the server, send a "Welcome" packet to the client first.

I assume you want to write a byte array into the `NetPacket`. If you are using the 2.1.0-pre version, `NetPacket` doesn't support primitive read/write arrays. If you are using the version on `develop` branch, when you write a byte array, it will first write the array length and then the data:
```c#
[int] byteArrayLength
[byte[]] content
```
Then, in the receive part, you need to call the `packet.Read<byte[]>()` method to get the read byte array you have serialized.

**Comment by neosatus** [comment]
Thanks for the quick response! I'm using the NuGet package so I assume 2.1.0. I'll try this out after work and get back to you.

**Comment by neosatus** [comment]
Got it working after learning a lot about how Serialization interacts with Assemblys. Thanks for the guidance.
