### ISSUE TITLE
Double receive processing

### ISSUE THREAD

**Issue by TeamNine** [Eastrall/Ether.Network#90]
Hello,
First to all thank you for your library, it's save time a lot =) 

Seems like I found double code in NetClient and SocketAsyncUtils. 

In NetClient class we have this handler:
```C#
this.Token.MessageHandler = data => this._receivingQueue.Add(data, this._cancelToken);
```
which is called in 
```C#
if (token.ReceivedMessageBytesCount == token.MessageSize.Value)
{
    byte[] messageData = packetProcessor.IncludeHeader
        ? token.HeaderData.Concat(token.MessageData).ToArray()
         : token.MessageData;

        token.Reset();
        token.MessageHandler?.Invoke(messageData);
}
```
And it adds to _receivingQueue already processed array, but in ProcessReceiveQueue it **process again**, and this method works in other thread which result to changing data between threads (thread unsafe behaviour)
```C#
byte[] buffer = this._receivingQueue.Take(this._cancelToken);
if (buffer == null)
    continue;
byte[] packetData = this.PacketProcessor.IncludeHeader
    ? this.Token.HeaderData.Concat(buffer).ToArray()
    : buffer;
    this.Token.HeaderData = null;
```

I received null argument exeption when had a lot of small packages in one time. Seems like in my case one thread proceesing received packages and another cleared my HeaderData and push invoke event to user.

**Comment by Eastrall** [comment]
Hi, thank you for reporting this issue. It can cause some problems if you decide to include the packet header in the stream.

I'll fix this for release 3.0.1.

**Comment by TeamNine** [comment]
Thank you. 
And it's additionaly cause problems because ProcessReceiveQueue and ReceiveData works in different threads but have access to **Token.HeaderData**, and while ReceiveData create HeaderData
```C#
if (token.HeaderData == null)
     token.HeaderData = new byte[packetProcessor.HeaderSize];
```
ProcessReceiveQueue clears it from other thread
```C#
this.Token.HeaderData = null;
```

**Comment by Eastrall** [comment]
After going through the code, I noticed that this code in `NetClient.ProcessReceiveQueue()` is useless:
```cs
byte[] packetData = this.PacketProcessor.IncludeHeader
                        ? this.Token.HeaderData.Concat(buffer).ToArray()
                        : buffer;
this.Token.HeaderData = null;
```
Because we already clear the header in the `SocketAsyncUtils.ReceiveData()` method. A PR will be done soon to fix this problem.

**Comment by lRaikeNl** [comment]
I will investigate on tuesday. Thanks for your fast reaction.

**Comment by Eastrall** [comment]
Issue seems to be solved. https://github.com/Eastrall/Ether.Network/issues/98#issuecomment-390881323
