### ISSUE TITLE
Retry when connect

### ISSUE THREAD

**Issue by namlai000** [Eastrall/Ether.Network#91]
I realized that when enter Connect() if the server isnt open the program stuck there infinite, even when the server comes back the program won't resume until the application restarted.
Can you implement retry function and after X retries throw exception that failed to connect OR retry infinite until server comes back online?

**Comment by lRaikeNl** [comment]
Got implemented in Commit [9c08225](https://github.com/Eastrall/Ether.Network/commit/9c08225dd4372a7af80e20c2d8bdb44cfa44c244)

I guess this can be closed.
