### ISSUE TITLE
HandleMessage not Executed

### ISSUE THREAD

**Issue by HurricanKai** [Eastrall/Ether.Network#96]
This coud possibly be me, but im going to ask anyways,
i have a connection with an Client, the OnConnected works normally, but in my protocol the *Client* Sends a packet first, thought, in my program, the "HandleMessage" Function is never executed, isnt this type of Protocol supported?

**Comment by PsychoPflanze** [comment]
Technically it should be working, can you provide code?

**Comment by Eastrall** [comment]
Hello, can you provide some code, so we can see what is possibly wrong and try to find a way to fix the problem ? Thank you.

**Comment by HurricanKai** [comment]
For me the problem was i wasnt using Ether on both sides, didnt have this problem when using Ether on both sides. Thought, it woud be nice if this woud be supported too, thought that is a thing for another issue.

**Comment by PsychoPflanze** [comment]
Oh okay, thank you for clearing that up, documentation is needed i guess :D

**Comment by Eastrall** [comment]
Yes, it's quite an important feature and I need to document it ASAP!
